### ISSUE TITLE
development roadmap

### ISSUE THREAD

**Issue by cole-brokamp** [geomarker-io/appc#3]
- [x] add just target for downloading/installing required geomarker data sources (w/o running any geomarker assessment code)
- [x] add small section about just and using it to run commands in the repository
- [x] #12
- [x] #11
  - double check data pipeline (missingness, summary statistics)
  - use OOB predictions to create CV error estimations, pred vs obs scatter plots (both in bag and out of bag by space)
  - include prediction tests for random locations and tests (but with fixed seed)
  - test for reasonable prediction magnitude, mean and var of preds across time and space
  - describe differences between test predictions for different model releases
- [ ] #10
  - alter NEI emissions predictors for these pollutants?
- [x] translate to a runnable 'thing' (SALT? GHA?)
- [x] build user prediction tools, API
  - add data tests for prediction outputs (reasonable prediction magnitude?)
  - version the api and prediction tool with {appc}
- [ ] release appc package on CRAN
  - just geomarker assessment functions? or entire model and predictions?
- [ ] quantify how model predictions retroactively change over time with updated models
  - publish this process and the change in models that provide "near real-time" ambient exposure estimates
